name: Deploy on Github Package

on:
  push:
    branches: ["main", "feat/cicd"]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Write env file from secret (decode base64)
        run: echo "${{ secrets.WORDPRESS_ENV_PROPERTIES }}" | base64 -d > .env

      - name: Build Docker image and push to Github Package
        run: |
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker build -t ghcr.io/xpeho/wordpress:latest .
            docker push ghcr.io/xpeho/wordpress:latest